name: Run API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run API tests
        id: run_tests
        run: |
          cd api_tests
          mvn clean test | tee mvn_output.log

      - name: Generate Allure Results
        run: |
          cd api_tests
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-report
          path: api_tests/allure-report

      - name: Summary of Test Results
        run: |
          echo "## Test Results Summary" >> summary.md
          echo "" >> summary.md
          echo "Tests run: ${{ steps.run_tests.outputs.tests }}" >> summary.md
          echo "Failures: ${{ steps.run_tests.outputs.failures }}" >> summary.md
          echo "Errors: ${{ steps.run_tests.outputs.errors }}" >> summary.md
          echo "Skipped: ${{ steps.run_tests.outputs.skipped }}" >> summary.md
          cat mvn_output.log >> summary.md
          echo "Results can be found in the Allure Report." >> summary.md

      - name: Upload Summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: summary.md
