name: Teste de Carga com K6

on:
  push:
    branches:
      - master  # ou a branch que você está usando

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Instalar K6
        run: |
          echo "Instalando K6..."
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Executar teste de carga
        run: |
          echo "Navegando até a pasta de testes e executando o teste de carga..."
          cd ~/Desktop/DURGA/Outsera/Outsera_Automation_Suite/load_tests
          k6 run load_test.js
