name: Teste de Carga com K6

on:
  push:
    branches:
      - master  # ou a branch que você está usando

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Baixar e instalar o K6
        run: |
          curl -sSL https://github.com/grafana/k6/releases/latest/download/k6-linux-amd64.tar.gz | tar -xz
          sudo install k6 /usr/local/bin/

      - name: Executar teste de carga
        run: |
          cd load_tests
          k6 run load_test.js
