name: Teste de Carga com K6

on:
  push:
    branches:
      - master  # ou a branch que você está usando

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Instalar Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:graphite-project/graphite
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Executar teste de carga
        run: |
          cd load_tests
          k6 run load_test.js
